services:
  - type: web
    name: youtube-ai-api
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERVERLESS
        value: "true"
      - key: MONGODB_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: YT_CLIENT_ID
        sync: false
      - key: YT_CLIENT_SECRET
        sync: false
      - key: YT_REDIRECT_URI
        value: https://youtube-ai-platform.onrender.com/api/youtube/callback
      - key: FRONTEND_URL
        value: https://youtube-ai-platform.vercel.app
